---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: ansible-kitchen
  ansible_verbose: true
  ansible_verbosity: 1
  requirements_path: requirements.yml

platforms:
  - name: ubuntu-14.04
  - name: centos-6.7

suites:
  - name: default

  - name: webservers
    excludes: 
      - centos-6.7
      
  - name: dbservers
    excludes:
      - ubuntu-14.04
